urg_node:
  ros__parameters:
    connection_type: "ethernet"
    ip_address: "192.168.0.10"
    ip_port: 10940
    laser_frame_id: "laser"
    angle_min: -3.14
    angle_max: 3.14
    cluster: 1
    skip: 0

